sudo: required

services:
  - docker

env:
  - distribution: fedora
    version: 27
  - distribution: centos
    version: 7
  - distribution: debian
    version: jessie

before_install:
  - 'sudo docker pull ${distribution}:${version}'

script:
  - container_id=$(mktemp)
